package adf.hr.model.bc.vo;


import adf.hr.model.bc.vo.common.DepartmentsVO;

import oracle.jbo.domain.Date;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;

import oracle.jbo.ViewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 18 15:59:24 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsVOImpl extends ViewObjectImpl implements DepartmentsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsVOImpl() {
    }
    public void masterDetail(String depName, String lastName, String email, Date hireDate, String jobID) {
//    ApplicationModule am =
//    //         this.getDBTransaction().getRootApplicationModule();
//       ADFUtils.getApplicationModuleForDataControl("AppModuleAM");
//     
//         
//             ViewObject depVO =am.findViewObject("Departments1");
//             Row depROW = depVO.createRow();
//             depROW.setAttribute("DepartmentName", depName);
//             depVO.insertRow(depROW);
//
//             ViewObject empVO = am.findViewObject("Employees3");
//             Row empROW = empVO.createRow();
//             empROW.setAttribute("LastName", lastName);
//             empROW.setAttribute("Email", email);
//             empROW.setAttribute("HireDate", hireDate);
//             empROW.setAttribute("JobId", jobID);
//             empVO.insertRow(empROW);
//
//             this.getDBTransaction().commit();
         
         
         
         
         
         }
}

