package adf.hr.model.bc.vo;

import adf.hr.model.bc.vo.common.EmployeesVO;

import oracle.jbo.VariableValueManager;
import oracle.jbo.common.ViewCriteriaImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 18 15:55:09 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends ViewObjectImpl implements EmployeesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }
    public String calculateEmployees(String firstName, String lastName) {
        ViewCriteriaImpl vc = (ViewCriteriaImpl) this.getViewCriteria("EmployeesViewCriteria");
        VariableValueManager vvm = this.ensureVariableManager();
        vvm.setVariableValue("firstNameVar", firstName);
        vvm.setVariableValue("lastNameVar", lastName);
        this.applyViewCriteria(vc);
        this.executeQuery();
        
        return Long.toString(this.getEstimatedRowCount());
    }

    /**
     * Returns the variable value for firstNameVar.
     * @return variable value for firstNameVar
     */
    public String getfirstNameVar() {
        return (String) ensureVariableManager().getVariableValue("firstNameVar");
    }

    /**
     * Sets <code>value</code> for variable firstNameVar.
     * @param value value to bind as firstNameVar
     */
    public void setfirstNameVar(String value) {
        ensureVariableManager().setVariableValue("firstNameVar", value);
    }

    /**
     * Returns the variable value for lastNameVar.
     * @return variable value for lastNameVar
     */
    public String getlastNameVar() {
        return (String) ensureVariableManager().getVariableValue("lastNameVar");
    }

    /**
     * Sets <code>value</code> for variable lastNameVar.
     * @param value value to bind as lastNameVar
     */
    public void setlastNameVar(String value) {
        ensureVariableManager().setVariableValue("lastNameVar", value);
    }
}

