package adf.hr.model.bc.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 18 16:08:44 EET 2018
// ---------------------------------------------------------------------
public interface EmployeesVO extends ViewObject {
    String calculateEmployees(String firstName, String lastName);
}

